# Generated by Django 4.2.4 on 2023-08-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('shop', 'shop'), ('admin', 'admin')], max_length=5, null=True),
        ),
    ]
