# Generated by Django 4.2.4 on 2023-09-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmsRegister',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
