# Generated by Django 4.2.4 on 2023-09-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_creator_boardmember_member_board_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcondition',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_conditions', to='home.board'),
        ),
    ]
